### ISSUE TITLE
Feature Request: Standardized Error Handling

### ISSUE THREAD

**Issue by ogunsoladebayo** [ogunsoladebayo/omni-cloud#1]
Implement a standardized error handling mechanism across all storage providers in the package (`AzureStorage`, `GoogleStorage`, etc.). This will ensure consistent error messages, better debugging, and improved user experience when handling exceptions or API errors.

#### Motivation
Currently, the package relies on provider-specific error handling and default behavior from libraries like `axios`. This can lead to inconsistent error messages and lack of clarity when something goes wrong. By introducing a unified error-handling approach, we can:
- Provide clear, human-readable error messages.
- Improve debuggability by including error codes and response details where necessary.
- Ensure consistent behavior across different storage providers.

#### Goals
- Implement a centralized error handling utility.
- Catch and format errors uniformly across all storage providers (Azure, Google, etc.).
- Ensure that HTTP and API errors (like 404s, 500s, etc.) are clearly communicated.
- Include useful metadata in the errors (e.g., provider name, file path, HTTP status code, etc.).
- Ensure that users can easily distinguish between different types of errors (e.g., network issues, authentication failures, file not found, etc.).

#### Proposed Solution
1. **Error Handling Utility**:
   - Create a utility module, `ErrorHandler.ts`, that can format and throw errors based on provider type and error details.
   - Example: `ErrorHandler.create(provider: string, message: string, code: number, details?: any)`.
   
2. **Provider-Specific Error Wrapping**:
   - Wrap all API requests in try/catch blocks within the storage provider classes.
   - When an error occurs, use the `ErrorHandler` to throw a standardized error message.

3. **Error Types**:
   - Define a set of standard error types (e.g., `AuthenticationError`, `FileNotFoundError`, `NetworkError`) that can be thrown based on the nature of the problem.

#### Example
When an error occurs while uploading a file, instead of showing a raw API error message, the package should throw a formatted error like this:
```typescript
{
  provider: 'GoogleStorage',
  error: 'AuthenticationError',
  message: 'Failed to authenticate with Google Cloud Storage',
  code: 401,
  details: { ... }
}
```

#### Tasks
- [ ] Create the `ErrorHandler.ts` utility.
- [ ] Implement standardized error handling in `AzureStorage.ts`.
- [ ] Implement standardized error handling in `GoogleStorage.ts`.
- [ ] Implement standardized error handling in `AwsStorage.ts`.
- [ ] Ensure consistent error formatting and handling across all methods (upload, download, list, delete).
- [ ] Write tests to validate that error handling works as expected and provides clear, consistent error messages.

#### Related Issues
- None at the moment.
