### ISSUE TITLE
Pluggable architecture for adding custom providers

### ISSUE THREAD

**Issue by ogunsoladebayo** [ogunsoladebayo/omni-cloud#5]
#### Description
Implement a pluggable architecture that allows developers to easily add custom storage providers to **Omni-Cloud** without modifying the core codebase. This will enable seamless integration of new providers, whether they are well-known cloud services or proprietary storage systems, enhancing the flexibility and extensibility of the package.

#### Motivation
Currently, **Omni-Cloud** supports a limited set of cloud storage providers. To make the package more versatile, we want to allow developers to add their own custom providers with minimal effort. This approach will benefit users who:
- Need to integrate with storage solutions not officially supported by the package.
- Have proprietary or self-hosted storage systems that require custom handling.
- Want to experiment with emerging or specialized storage services.

Implementing a pluggable architecture will also reduce the maintenance overhead of adding new providers directly to the core library.

#### Goals
- Define a clear interface that custom providers must implement.
- Create a mechanism to register and use custom providers dynamically.
- Ensure that custom providers integrate seamlessly with existing functionality (upload, download, delete operations).
- Maintain backward compatibility with existing providers.

#### Proposed Solution
1. **Provider Interface Definition**:
   - Extend the existing `IStorageProvider` interface to include detailed requirements that custom providers must implement.
   - Example interface methods:
     - `upload(localPath: string, remotePath: string): Promise<void>`
     - `download(remotePath: string, localPath: string): Promise<void>`
     - `delete(filePath: string): Promise<void>`

2. **Provider Registration System**:
   - Implement a `ProviderRegistry` that allows developers to register their custom providers by name.
   - Example registration method: `ProviderRegistry.register('MyCustomProvider', MyCustomProviderClass)`.
   - Ensure that the `ProviderFactory` can instantiate both built-in and custom providers using this registry.

3. **Documentation and Examples**:
   - Provide clear documentation on how to create and register a custom provider.
   - Include an example of a minimal custom provider implementation in the README.

#### Example
Developers should be able to add a new custom provider like this:
```typescript
import { IStorageProvider, ProviderRegistry } from 'omni-cloud';

class MyCustomProvider implements IStorageProvider {
  async upload(localPath: string, remotePath: string): Promise<void> {
    // Custom implementation for uploading files
  }

  async download(remotePath: string, localPath: string): Promise<void> {
    // Custom implementation for downloading files
  }

  async delete(filePath: string): Promise<void> {
    // Custom implementation for deleting files
  }
}

// Register the custom provider
ProviderRegistry.register('MyCustomProvider', MyCustomProvider);
```

#### Tasks
- [ ] Extend the `IStorageProvider` interface to standardize requirements for custom providers.
- [ ] Implement the `ProviderRegistry` to handle provider registration and management.
- [ ] Update the `ProviderFactory` to utilize the `ProviderRegistry` for creating providers.
- [ ] Add unit tests to ensure the pluggable architecture works as expected with custom providers.
- [ ] Update documentation with a guide on how to create and use custom providers.
- [ ] Include an example custom provider in the package's examples directory.

#### Related Issues
- None at the moment.

#### Additional Context
This feature will empower developers to integrate **Omni-Cloud** with virtually any storage system, making the package more versatile and adaptable to diverse requirements. By adopting a pluggable architecture, we ensure that the package remains future-proof and scalable.
